// build-glyphs.js — read selected zdic SVGs, normalize to currentColor, emit js/glyphs.js
const fs = require('fs');
const path = require('path');

const SRC = 'C:/Users/caelum/Desktop/创意河南-殷墟甲骨文信息可视化/01-资料研究/字形参考';
const OUT = 'C:/Users/caelum/Desktop/甲骨寻踪-H5/js/glyphs.js';

// char -> [jiagu#, jinwen#, xiaozhuan#] per 字形遴选表-v1
const SEL = {
  '日': [1, 3, 1], '月': [1, 4, 1], '山': [3, 3, 1], '水': [1, 1, 1],
  '雨': [1, 2, 1], '目': [1, 1, 1], '家': [1, 1, 1], '马': [1, 8, 1],
  '鹿': [1, 4, 1], '休': [1, 1, 1], '明': [1, 2, 1], '河': [1, 1, 1],
};

// near-white: every RGB channel >= 250 (zdic watermark color family)
function isNearWhite(hex) {
  const n = parseInt(hex.slice(1), 16);
  return [16, 8, 0].every(sh => ((n >> sh) & 255) >= 250);
}

function normalize(svg) {
  let s = svg;
  // 1) drop watermark <g> groups with near-white fill
  s = s.replace(/<g[^>]*fill="(#[0-9a-fA-F]{6})"[^>]*>[\s\S]*?<\/g>/g, (m, hex) =>
    isNearWhite(hex) ? '' : m);
  // 2) drop self-closing elements with near-white fill (watermark paths)
  s = s.replace(/<[a-zA-Z]+[^>]*fill="(#[0-9a-fA-F]{6})"[^>]*\/>/g, (m, hex) =>
    isNearWhite(hex) ? '' : m);
  // force fill/stroke color attrs to currentColor
  s = s.replace(/\sfill="(?:#[0-9a-fA-F]{3,8}|black|rgb\([^)]*\))"/g, ' fill="currentColor"');
  s = s.replace(/\sstroke="(?:#[0-9a-fA-F]{3,8}|black|rgb\([^)]*\))"/g, ' stroke="currentColor"');
  // add fill on root svg if absent
  if (!/<svg[^>]*\sfill=/.test(s)) {
    s = s.replace(/<svg/, '<svg fill="currentColor"');
  }
  return s;
}

const sets = { jiagu: {}, jinwen: {}, xiaozhuan: {} };
for (const [ch, nums] of Object.entries(SEL)) {
  const files = [`jiagu_${nums[0]}.svg`, `jinwen_${nums[1]}.svg`, `xiaozhuan_${nums[2]}.svg`];
  const keys = ['jiagu', 'jinwen', 'xiaozhuan'];
  files.forEach((f, i) => {
    const p = path.join(SRC, ch, f);
    if (!fs.existsSync(p)) throw new Error(`MISSING ${p}`);
    sets[keys[i]][ch] = normalize(fs.readFileSync(p, 'utf8').replace(/\r?\n/g, '').trim());
  });
}

function emit(name, obj) {
  const body = Object.entries(obj).map(([k, v]) =>
    `  ${JSON.stringify(k)}: ${JSON.stringify(v)}`).join(',\n');
  return `const ${name} = {\n${body}\n};\n`;
}
out = `// glyphs.js — auto-generated by build-glyphs.js from zdic SVGs (selected per 字形遴选表-v1)
// viewBox 400x400, normalized to currentColor. Source: 汉典字源库 traces of real inscriptions.

${emit('GLYPHS_JIAGU', sets.jiagu)}
${emit('GLYPHS_JINWEN', sets.jinwen)}
${emit('GLYPHS_XIAOZHUAN', sets.xiaozhuan)}`;

fs.writeFileSync(OUT, out, 'utf8');
console.log('glyphs.js written:', out.length, 'bytes,', Object.keys(sets.jiagu).length, 'chars');
